"""Immutable contracts for deterministic job text normalization.

The normalization pipeline is not implemented yet. See the phase 1 ADR.
"""

from normietext.errors import (
    ErrorCode,
    InputValidationError,
    ModelValidationError,
    NormalizationError,
    OutputInvariantError,
    PolicyMismatchError,
    PolicyValidationError,
    ResourceLimitError,
)
from normietext.models import (
    Annotation,
    AnnotationKind,
    Association,
    Block,
    BlockKind,
    DocumentPhase,
    Edit,
    ExtractionError,
    ExtractionStatus,
    FieldFailure,
    FieldInput,
    FieldOutcome,
    FieldStatus,
    FrozenMap,
    InputField,
    Issue,
    IssueCode,
    JobField,
    JobInputRecord,
    Manifest,
    NormalizedField,
    NormalizedJobRecord,
    Origin,
    OriginPrecision,
    ParsedDocument,
    RecordStatus,
    SourceEvidence,
    SourceFormat,
    Span,
    VersionedArtifact,
    freeze_json,
)
from normietext.policy import NormalizationPolicy, ResourceLimits

__all__ = [
    "Annotation",
    "AnnotationKind",
    "Association",
    "Block",
    "BlockKind",
    "DocumentPhase",
    "Edit",
    "ErrorCode",
    "ExtractionError",
    "ExtractionStatus",
    "FieldFailure",
    "FieldInput",
    "FieldOutcome",
    "FieldStatus",
    "FrozenMap",
    "InputField",
    "InputValidationError",
    "Issue",
    "IssueCode",
    "JobField",
    "JobInputRecord",
    "Manifest",
    "ModelValidationError",
    "NormalizationError",
    "NormalizationPolicy",
    "NormalizedField",
    "NormalizedJobRecord",
    "Origin",
    "OriginPrecision",
    "OutputInvariantError",
    "ParsedDocument",
    "PolicyMismatchError",
    "PolicyValidationError",
    "RecordStatus",
    "ResourceLimitError",
    "ResourceLimits",
    "SourceEvidence",
    "SourceFormat",
    "Span",
    "VersionedArtifact",
    "freeze_json",
]
