"""Effective, reproducible environment identity. Never invokes Git or the network."""

import hashlib
import importlib
import json
import platform
import sys
import sysconfig
import unicodedata
from functools import lru_cache
from importlib.metadata import distribution, version
from importlib.resources import files
from pathlib import Path
from zipfile import ZipFile

from normietext._validation import require
from normietext.models import Manifest, VersionedArtifact
from normietext.policy import NormalizationPolicy
from normietext.serialization import canonical_hash

_DEFAULT_POLICY = NormalizationPolicy()


_DIRECT = ("beautifulsoup4", "emoji", "ftfy", "lxml", "regex")
# Runtime closure is fixed by the baseline lock, not incidentally installed packages.
_RUNTIME = (*_DIRECT, "soupsieve", "typing-extensions", "wcwidth")


def code_fingerprint() -> str:
    root = files("normietext")
    content: dict[str, str] = {}

    def visit(directory: object, prefix: str = "") -> None:
        # Traversable is intentionally resolved from resources, not a checkout path.
        from importlib.resources.abc import Traversable

        assert isinstance(directory, Traversable)
        for item in directory.iterdir():
            name = prefix + item.name
            if item.is_dir() and item.name != "__pycache__":
                visit(item, name + "/")
            elif item.is_file() and (name.endswith(".py") or name == "py.typed"):
                content[name] = hashlib.sha256(item.read_bytes()).hexdigest()

    visit(root)
    return canonical_hash(content)


@lru_cache(maxsize=1)
def table_artifacts() -> tuple[VersionedArtifact, ...]:
    root = files("normietext").joinpath("data")
    manifest_bytes = root.joinpath("unicode_policy_manifest.json").read_bytes()
    manifest = json.loads(manifest_bytes)
    artifacts = [
        VersionedArtifact(
            "unicode_policy_manifest.json",
            manifest["table_version"],
            hashlib.sha256(manifest_bytes).hexdigest(),
        )
    ]
    for name, expected in sorted(manifest["files"].items()):
        require(".." not in name.split("/") and not name.startswith("/"), "Invalid table path")
        digest = hashlib.sha256(root.joinpath(name).read_bytes()).hexdigest()
        require(digest == expected, "Packaged table integrity mismatch")
        artifacts.append(VersionedArtifact(name, manifest["table_version"], digest))
    return tuple(sorted(artifacts, key=lambda item: item.name))


def policy_hash(policy: NormalizationPolicy) -> str:
    return canonical_hash(
        {"domain": "normietext.policy.v1", "effective": policy, "tables": table_artifacts()}
    )


@lru_cache(maxsize=1)
def _runtime() -> tuple[tuple[tuple[str, str], ...], tuple[VersionedArtifact, ...]]:
    dependencies = tuple(sorted((name, version(name)) for name in _RUNTIME))
    artifacts = []
    for name, installed_version in dependencies:
        dist = distribution(name)
        entries = dist.files
        require(entries is not None, "Installed distribution has no file inventory")
        assert entries is not None
        hashes = {}
        for entry in entries:
            # Ignore generated bytecode, install paths, scripts and installer metadata.
            if (
                ".." in entry.parts
                or entry.suffix == ".pyc"
                or entry.name
                in (
                    "RECORD",
                    "INSTALLER",
                    "REQUESTED",
                    "direct_url.json",
                    "uv_cache.json",
                )
            ):
                continue
            path = Path(entry.locate())
            if path.is_file():
                hashes[str(entry).replace("\\", "/")] = hashlib.sha256(
                    path.read_bytes()
                ).hexdigest()
        require(bool(hashes), "Installed distribution has no hashable content")
        artifacts.append(
            VersionedArtifact("installed:" + name, installed_version, canonical_hash(hashes))
        )
    runtime = {
        "implementation": platform.python_implementation(),
        "version": platform.python_version(),
        "ucd": unicodedata.unidata_version,
        "cache_tag": sys.implementation.cache_tag,
        "gil_disabled": bool(sysconfig.get_config_var("Py_GIL_DISABLED")),
        "platform": sys.platform,
        "machine": platform.machine(),
        "byteorder": sys.byteorder,
    }
    artifacts.append(
        VersionedArtifact("python-runtime", platform.python_version(), canonical_hash(runtime))
    )
    return dependencies, tuple(artifacts)


def wheel_artifact(path: Path) -> VersionedArtifact:
    """Hash an actual retained wheel, not a filename or an assumed lockfile candidate.

    The deployer must supply the exact wheels used for installation; installed
    fingerprints are recorded independently and never mislabeled as wheel hashes.
    """
    from email.parser import BytesParser

    with ZipFile(path) as archive:
        names = [name for name in archive.namelist() if name.endswith(".dist-info/METADATA")]
        require(len(names) == 1, "Wheel must contain exactly one distribution metadata file")
        metadata = BytesParser().parsebytes(archive.read(names[0]))
    name, release = metadata.get("Name"), metadata.get("Version")
    require(isinstance(name, str) and isinstance(release, str), "Invalid wheel metadata")
    assert isinstance(name, str) and isinstance(release, str)
    normalized = name.lower().replace("_", "-")
    require(normalized in _RUNTIME, "Wheel is not in the runtime dependency closure")
    require(version(normalized) == release, "Wheel/installed version mismatch")
    return VersionedArtifact(
        "wheel:" + normalized, release, hashlib.sha256(path.read_bytes()).hexdigest()
    )


def create_manifest(
    policy: NormalizationPolicy = _DEFAULT_POLICY,
    *,
    wheels: tuple[Path, ...] = (),
    require_wheels: bool = False,
) -> Manifest:
    dependencies, installed = _runtime()
    artifacts = tuple(wheel_artifact(path) for path in wheels)
    if require_wheels:
        require(
            {item.name for item in artifacts} == {"wheel:" + name for name in _RUNTIME},
            "Production manifest requires the complete installation wheel inventory",
        )
    root = files("normietext").joinpath("data")
    build_file = root.joinpath("build_info.json")
    fingerprint = code_fingerprint()
    if build_file.is_file():
        build = json.loads(build_file.read_bytes())
        require(build["code_sha256"] == fingerprint, "Code differs from build provenance")
        revision = build["code_revision"]
    else:
        revision = "source-tree:" + fingerprint
    etree = importlib.import_module("lxml.etree")
    libxml = ".".join(map(str, etree.LIBXML_VERSION))
    native = VersionedArtifact(
        "lxml-build",
        version("lxml"),
        canonical_hash(
            {
                "compiled_libxml2": etree.LIBXML_COMPILED_VERSION,
                "runtime_libxml2": etree.LIBXML_VERSION,
            }
        ),
    )
    return Manifest(
        policy.schema_version,
        policy.normalization_version,
        policy.policy_id,
        policy_hash(policy),
        revision,
        platform.python_version(),
        unicodedata.unidata_version,
        "beautifulsoup4:lxml",
        libxml,
        dependencies,
        table_artifacts(),
        tuple(
            sorted(
                (
                    *installed,
                    *artifacts,
                    native,
                    VersionedArtifact("normietext-code", version("normietext"), fingerprint),
                ),
                key=lambda item: item.name,
            )
        ),
    )
